// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qKkrPgjS99ztd_Ne_y3bH4DjttLpJHA',
    appId: '1:58693485475:web:e744bf465957084c019016',
    messagingSenderId: '58693485475',
    projectId: 'flutterredditchatapp',
    authDomain: 'flutterredditchatapp.firebaseapp.com',
    storageBucket: 'flutterredditchatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7GaHqeRV3lLm459Cyb4soIDMdcxBEXc',
    appId: '1:58693485475:android:cc32f2e70295669f019016',
    messagingSenderId: '58693485475',
    projectId: 'flutterredditchatapp',
    storageBucket: 'flutterredditchatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMFVH1VkLHwKx7iTL4X6JMaoKBm2S3TEI',
    appId: '1:58693485475:ios:205fa813d628cb11019016',
    messagingSenderId: '58693485475',
    projectId: 'flutterredditchatapp',
    storageBucket: 'flutterredditchatapp.appspot.com',
    iosBundleId: 'com.example.flutterCommunityReditChatApp',
  );
}
